import React, { useState, useEffect } from 'react';
import { StyleSheet, View, Text, ScrollView, ActivityIndicator, Image, TouchableOpacity, Share } from 'react-native';
import { db,auth ,app} from '../FirebaseConfig'; 
export default function Singup({ email, sname }) {
  const [code, setCode] = useState('');
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const ref = app.storage().ref().child(`${email}/${sname}-code.js`);
    
    ref.getDownloadURL()
      .then((url) => {
        fetch(url)
          .then((response) => response.text())
          .then((text) => {
            setCode(text);
            setLoading(false);
          });
      })
      .catch((error) => {
        console.error(error);
        setLoading(false);
      });

    // Cleanup (not strictly necessary in this case)
    return () => {
      // Cleanup tasks here, if any
    };
  }, [email, sname]);

  const shareEvent = () => {
    try {
      const result = Share.share({
        message: code,
        title: `Layout: ${sname.replace("_", " ")} - code generated by auto layout`,
      });

      if (result.action === Share.sharedAction) {
        if (result.activityType) {
          // shared with activity type
        } else {
          // shared
        }
      } else if (result.action === Share.dismissedAction) {
        // dismissed
      }
    } catch (error) {
      alert(error.message);
    }
  };

  if (loading) {
    return (
      <View style={styles.container}>
        <ActivityIndicator size={"large"} color={"#66BB6A"} />
      </View>
    );
  }

  return (
    <View style={styles.container}>
      <ScrollView contentContainerStyle={styles.scrollViewContent}>
        <Text style={styles.code} selectable={true}>
          {code}
        </Text>
      </ScrollView>

      <TouchableOpacity
        activeOpacity={0.5}
        style={styles.TouchableOpacityStyle}
        onPress={shareEvent}
      >
        <Image source={require('../assets/share.png')} style={styles.FloatingButtonStyle} />
      </TouchableOpacity>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
  },
  scrollViewContent: {
    flexGrow: 1,
    justifyContent: 'center',
    padding: 16,
  },
  code: {
    fontFamily: 'monospace',
    fontSize: 12,
    textAlign: 'center',
    marginVertical: 10,
  },
  TouchableOpacityStyle: {
    position: 'absolute',
    width: 50,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    right: 20,
    bottom: 20,
    backgroundColor: '#66BB6A',
    borderRadius: 64,
    shadowColor: 'rgba(0,0,0, .4)',
    shadowOffset: { height: 1, width: 1 },
    shadowOpacity: 1,
    shadowRadius: 1,
    elevation: 5,
  },
  FloatingButtonStyle: {
    resizeMode: 'contain',
    width: 30,
    height: 30,
  },
});
